<?php
/**
 * CategoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Procurement API
 *
 * ConnectWise Procurement API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Procurement;

/**
 * CategoryTest Class Doc Comment
 *
 * @category    Class */
// * @description Category
/**
 * @package     Spinen\ConnectWise\Clients\Procurement
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CategoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Category"
     */
    public function testCategory()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "inactive_flag"
     */
    public function testPropertyInactiveFlag()
    {

    }

    /**
     * Test attribute "price_level_xref"
     */
    public function testPropertyPriceLevelXref()
    {

    }

    /**
     * Test attribute "integration_xref"
     */
    public function testPropertyIntegrationXref()
    {

    }

    /**
     * Test attribute "location_ids"
     */
    public function testPropertyLocationIds()
    {

    }

    /**
     * Test attribute "add_all_locations"
     */
    public function testPropertyAddAllLocations()
    {

    }

    /**
     * Test attribute "remove_all_locations"
     */
    public function testPropertyRemoveAllLocations()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
