<?php
/**
 * ProductItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Procurement API
 *
 * ConnectWise Procurement API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Procurement;

/**
 * ProductItemTest Class Doc Comment
 *
 * @category    Class */
// * @description ProductItem
/**
 * @package     Spinen\ConnectWise\Clients\Procurement
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ProductItem"
     */
    public function testProductItem()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "catalog_item"
     */
    public function testPropertyCatalogItem()
    {

    }

    /**
     * Test attribute "charge_to_id"
     */
    public function testPropertyChargeToId()
    {

    }

    /**
     * Test attribute "charge_to_type"
     */
    public function testPropertyChargeToType()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "sequence_number"
     */
    public function testPropertySequenceNumber()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {

    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {

    }

    /**
     * Test attribute "price_method"
     */
    public function testPropertyPriceMethod()
    {

    }

    /**
     * Test attribute "billable_option"
     */
    public function testPropertyBillableOption()
    {

    }

    /**
     * Test attribute "agreement"
     */
    public function testPropertyAgreement()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "business_unit_id"
     */
    public function testPropertyBusinessUnitId()
    {

    }

    /**
     * Test attribute "vendor"
     */
    public function testPropertyVendor()
    {

    }

    /**
     * Test attribute "vendor_sku"
     */
    public function testPropertyVendorSku()
    {

    }

    /**
     * Test attribute "taxable_flag"
     */
    public function testPropertyTaxableFlag()
    {

    }

    /**
     * Test attribute "dropship_flag"
     */
    public function testPropertyDropshipFlag()
    {

    }

    /**
     * Test attribute "special_order_flag"
     */
    public function testPropertySpecialOrderFlag()
    {

    }

    /**
     * Test attribute "phase_product_flag"
     */
    public function testPropertyPhaseProductFlag()
    {

    }

    /**
     * Test attribute "cancelled_flag"
     */
    public function testPropertyCancelledFlag()
    {

    }

    /**
     * Test attribute "quantity_cancelled"
     */
    public function testPropertyQuantityCancelled()
    {

    }

    /**
     * Test attribute "cancelled_reason"
     */
    public function testPropertyCancelledReason()
    {

    }

    /**
     * Test attribute "customer_description"
     */
    public function testPropertyCustomerDescription()
    {

    }

    /**
     * Test attribute "internal_notes"
     */
    public function testPropertyInternalNotes()
    {

    }

    /**
     * Test attribute "product_supplied_flag"
     */
    public function testPropertyProductSuppliedFlag()
    {

    }

    /**
     * Test attribute "sub_contractor_ship_to_id"
     */
    public function testPropertySubContractorShipToId()
    {

    }

    /**
     * Test attribute "sub_contractor_amount_limit"
     */
    public function testPropertySubContractorAmountLimit()
    {

    }

    /**
     * Test attribute "recurring"
     */
    public function testPropertyRecurring()
    {

    }

    /**
     * Test attribute "sla"
     */
    public function testPropertySla()
    {

    }

    /**
     * Test attribute "entity_type"
     */
    public function testPropertyEntityType()
    {

    }

    /**
     * Test attribute "forecast_detail_id"
     */
    public function testPropertyForecastDetailId()
    {

    }

    /**
     * Test attribute "cancelled_by"
     */
    public function testPropertyCancelledBy()
    {

    }

    /**
     * Test attribute "cancelled_date"
     */
    public function testPropertyCancelledDate()
    {

    }

    /**
     * Test attribute "warehouse"
     */
    public function testPropertyWarehouse()
    {

    }

    /**
     * Test attribute "warehouse_bin"
     */
    public function testPropertyWarehouseBin()
    {

    }

    /**
     * Test attribute "purchase_date"
     */
    public function testPropertyPurchaseDate()
    {

    }

    /**
     * Test attribute "integration_x_ref"
     */
    public function testPropertyIntegrationXRef()
    {

    }

    /**
     * Test attribute "list_price"
     */
    public function testPropertyListPrice()
    {

    }

    /**
     * Test attribute "serial_number_ids"
     */
    public function testPropertySerialNumberIds()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "forecast_status"
     */
    public function testPropertyForecastStatus()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

    /**
     * Test attribute "bypass_forecast_update"
     */
    public function testPropertyBypassForecastUpdate()
    {

    }

}
