<?php
/**
 * ProductComponentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Procurement API
 *
 * ConnectWise Procurement API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Procurement;

/**
 * ProductComponentTest Class Doc Comment
 *
 * @category    Class */
// * @description ProductComponent
/**
 * @package     Spinen\ConnectWise\Clients\Procurement
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductComponentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ProductComponent"
     */
    public function testProductComponent()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "sequence_number"
     */
    public function testPropertySequenceNumber()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "catalog_item"
     */
    public function testPropertyCatalogItem()
    {

    }

    /**
     * Test attribute "hide_price_flag"
     */
    public function testPropertyHidePriceFlag()
    {

    }

    /**
     * Test attribute "hide_item_identifier_flag"
     */
    public function testPropertyHideItemIdentifierFlag()
    {

    }

    /**
     * Test attribute "hide_description_flag"
     */
    public function testPropertyHideDescriptionFlag()
    {

    }

    /**
     * Test attribute "hide_quantity_flag"
     */
    public function testPropertyHideQuantityFlag()
    {

    }

    /**
     * Test attribute "vendor"
     */
    public function testPropertyVendor()
    {

    }

    /**
     * Test attribute "parent_product_item"
     */
    public function testPropertyParentProductItem()
    {

    }

    /**
     * Test attribute "product_item"
     */
    public function testPropertyProductItem()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
