<?php
/**
 * ProductPickingShippingDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Procurement API
 *
 * ConnectWise Procurement API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Procurement;

/**
 * ProductPickingShippingDetailTest Class Doc Comment
 *
 * @category    Class */
// * @description ProductPickingShippingDetail
/**
 * @package     Spinen\ConnectWise\Clients\Procurement
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductPickingShippingDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ProductPickingShippingDetail"
     */
    public function testProductPickingShippingDetail()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "picked_quantity"
     */
    public function testPropertyPickedQuantity()
    {

    }

    /**
     * Test attribute "shipped_quantity"
     */
    public function testPropertyShippedQuantity()
    {

    }

    /**
     * Test attribute "warehouse"
     */
    public function testPropertyWarehouse()
    {

    }

    /**
     * Test attribute "warehouse_bin"
     */
    public function testPropertyWarehouseBin()
    {

    }

    /**
     * Test attribute "shipment_method"
     */
    public function testPropertyShipmentMethod()
    {

    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {

    }

    /**
     * Test attribute "serial_number_ids"
     */
    public function testPropertySerialNumberIds()
    {

    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {

    }

    /**
     * Test attribute "product_item"
     */
    public function testPropertyProductItem()
    {

    }

    /**
     * Test attribute "line_number"
     */
    public function testPropertyLineNumber()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
