<?php
/**
 * AdjustmentTypesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Procurement API
 *
 * ConnectWise Procurement API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Procurement;

use \Spinen\ConnectWise\Clients\Procurement\Configuration;
use \Spinen\ConnectWise\Clients\Procurement\ApiClient;
use \Spinen\ConnectWise\Clients\Procurement\ApiException;
use \Spinen\ConnectWise\Clients\Procurement\ObjectSerializer;

/**
 * AdjustmentTypesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdjustmentTypesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for procurementAdjustmentsTypesCountGet
     *
     * .
     *
     */
    public function testProcurementAdjustmentsTypesCountGet()
    {

    }

    /**
     * Test case for procurementAdjustmentsTypesGet
     *
     * .
     *
     */
    public function testProcurementAdjustmentsTypesGet()
    {

    }

    /**
     * Test case for procurementAdjustmentsTypesIdDelete
     *
     * .
     *
     */
    public function testProcurementAdjustmentsTypesIdDelete()
    {

    }

    /**
     * Test case for procurementAdjustmentsTypesIdGet
     *
     * .
     *
     */
    public function testProcurementAdjustmentsTypesIdGet()
    {

    }

    /**
     * Test case for procurementAdjustmentsTypesIdPatch
     *
     * .
     *
     */
    public function testProcurementAdjustmentsTypesIdPatch()
    {

    }

    /**
     * Test case for procurementAdjustmentsTypesIdPut
     *
     * .
     *
     */
    public function testProcurementAdjustmentsTypesIdPut()
    {

    }

    /**
     * Test case for procurementAdjustmentsTypesPost
     *
     * .
     *
     */
    public function testProcurementAdjustmentsTypesPost()
    {

    }

}
