<?php
/**
 * AdjustmentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Procurement API
 *
 * ConnectWise Procurement API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Procurement;

use \Spinen\ConnectWise\Clients\Procurement\Configuration;
use \Spinen\ConnectWise\Clients\Procurement\ApiClient;
use \Spinen\ConnectWise\Clients\Procurement\ApiException;
use \Spinen\ConnectWise\Clients\Procurement\ObjectSerializer;

/**
 * AdjustmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdjustmentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for procurementAdjustmentsCountGet
     *
     * .
     *
     */
    public function testProcurementAdjustmentsCountGet()
    {

    }

    /**
     * Test case for procurementAdjustmentsGet
     *
     * .
     *
     */
    public function testProcurementAdjustmentsGet()
    {

    }

    /**
     * Test case for procurementAdjustmentsIdDelete
     *
     * .
     *
     */
    public function testProcurementAdjustmentsIdDelete()
    {

    }

    /**
     * Test case for procurementAdjustmentsIdGet
     *
     * .
     *
     */
    public function testProcurementAdjustmentsIdGet()
    {

    }

    /**
     * Test case for procurementAdjustmentsIdPatch
     *
     * .
     *
     */
    public function testProcurementAdjustmentsIdPatch()
    {

    }

    /**
     * Test case for procurementAdjustmentsIdPut
     *
     * .
     *
     */
    public function testProcurementAdjustmentsIdPut()
    {

    }

    /**
     * Test case for procurementAdjustmentsPost
     *
     * .
     *
     */
    public function testProcurementAdjustmentsPost()
    {

    }

}
