<?php
/**
 * CatalogsItemApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Procurement API
 *
 * ConnectWise Procurement API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Procurement;

use \Spinen\ConnectWise\Clients\Procurement\Configuration;
use \Spinen\ConnectWise\Clients\Procurement\ApiClient;
use \Spinen\ConnectWise\Clients\Procurement\ApiException;
use \Spinen\ConnectWise\Clients\Procurement\ObjectSerializer;

/**
 * CatalogsItemApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CatalogsItemApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for procurementCatalogCatalogItemIdentifierQuantityOnHandGet
     *
     * .
     *
     */
    public function testProcurementCatalogCatalogItemIdentifierQuantityOnHandGet()
    {

    }

    /**
     * Test case for procurementCatalogCountGet
     *
     * .
     *
     */
    public function testProcurementCatalogCountGet()
    {

    }

    /**
     * Test case for procurementCatalogGet
     *
     * .
     *
     */
    public function testProcurementCatalogGet()
    {

    }

    /**
     * Test case for procurementCatalogIdDelete
     *
     * .
     *
     */
    public function testProcurementCatalogIdDelete()
    {

    }

    /**
     * Test case for procurementCatalogIdGet
     *
     * .
     *
     */
    public function testProcurementCatalogIdGet()
    {

    }

    /**
     * Test case for procurementCatalogIdPatch
     *
     * .
     *
     */
    public function testProcurementCatalogIdPatch()
    {

    }

    /**
     * Test case for procurementCatalogIdPut
     *
     * .
     *
     */
    public function testProcurementCatalogIdPut()
    {

    }

    /**
     * Test case for procurementCatalogPost
     *
     * .
     *
     */
    public function testProcurementCatalogPost()
    {

    }

}
