<?php
/**
 * ManufacturersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Procurement API
 *
 * ConnectWise Procurement API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Procurement;

use \Spinen\ConnectWise\Clients\Procurement\Configuration;
use \Spinen\ConnectWise\Clients\Procurement\ApiClient;
use \Spinen\ConnectWise\Clients\Procurement\ApiException;
use \Spinen\ConnectWise\Clients\Procurement\ObjectSerializer;

/**
 * ManufacturersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ManufacturersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for procurementManufacturersCountGet
     *
     * .
     *
     */
    public function testProcurementManufacturersCountGet()
    {

    }

    /**
     * Test case for procurementManufacturersGet
     *
     * .
     *
     */
    public function testProcurementManufacturersGet()
    {

    }

    /**
     * Test case for procurementManufacturersIdDelete
     *
     * .
     *
     */
    public function testProcurementManufacturersIdDelete()
    {

    }

    /**
     * Test case for procurementManufacturersIdGet
     *
     * .
     *
     */
    public function testProcurementManufacturersIdGet()
    {

    }

    /**
     * Test case for procurementManufacturersIdPatch
     *
     * .
     *
     */
    public function testProcurementManufacturersIdPatch()
    {

    }

    /**
     * Test case for procurementManufacturersIdPut
     *
     * .
     *
     */
    public function testProcurementManufacturersIdPut()
    {

    }

    /**
     * Test case for procurementManufacturersPost
     *
     * .
     *
     */
    public function testProcurementManufacturersPost()
    {

    }

}
