<?php
/**
 * ProductComponentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Procurement API
 *
 * ConnectWise Procurement API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Procurement;

use \Spinen\ConnectWise\Clients\Procurement\Configuration;
use \Spinen\ConnectWise\Clients\Procurement\ApiClient;
use \Spinen\ConnectWise\Clients\Procurement\ApiException;
use \Spinen\ConnectWise\Clients\Procurement\ObjectSerializer;

/**
 * ProductComponentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductComponentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for procurementProductsIdComponentsComponentIdDelete
     *
     * .
     *
     */
    public function testProcurementProductsIdComponentsComponentIdDelete()
    {

    }

    /**
     * Test case for procurementProductsIdComponentsComponentIdGet
     *
     * .
     *
     */
    public function testProcurementProductsIdComponentsComponentIdGet()
    {

    }

    /**
     * Test case for procurementProductsIdComponentsComponentIdPatch
     *
     * .
     *
     */
    public function testProcurementProductsIdComponentsComponentIdPatch()
    {

    }

    /**
     * Test case for procurementProductsIdComponentsComponentIdPut
     *
     * .
     *
     */
    public function testProcurementProductsIdComponentsComponentIdPut()
    {

    }

    /**
     * Test case for procurementProductsIdComponentsCountGet
     *
     * .
     *
     */
    public function testProcurementProductsIdComponentsCountGet()
    {

    }

    /**
     * Test case for procurementProductsIdComponentsGet
     *
     * .
     *
     */
    public function testProcurementProductsIdComponentsGet()
    {

    }

    /**
     * Test case for procurementProductsIdComponentsPost
     *
     * .
     *
     */
    public function testProcurementProductsIdComponentsPost()
    {

    }

}
