<?php
/**
 * UnitOfMeasureConversionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Procurement API
 *
 * ConnectWise Procurement API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Procurement;

use \Spinen\ConnectWise\Clients\Procurement\Configuration;
use \Spinen\ConnectWise\Clients\Procurement\ApiClient;
use \Spinen\ConnectWise\Clients\Procurement\ApiException;
use \Spinen\ConnectWise\Clients\Procurement\ObjectSerializer;

/**
 * UnitOfMeasureConversionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Procurement
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UnitOfMeasureConversionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for procurementUnitOfMeasuresIdConversionsConversionIdDelete
     *
     * .
     *
     */
    public function testProcurementUnitOfMeasuresIdConversionsConversionIdDelete()
    {

    }

    /**
     * Test case for procurementUnitOfMeasuresIdConversionsConversionIdGet
     *
     * .
     *
     */
    public function testProcurementUnitOfMeasuresIdConversionsConversionIdGet()
    {

    }

    /**
     * Test case for procurementUnitOfMeasuresIdConversionsConversionIdPatch
     *
     * .
     *
     */
    public function testProcurementUnitOfMeasuresIdConversionsConversionIdPatch()
    {

    }

    /**
     * Test case for procurementUnitOfMeasuresIdConversionsConversionIdPut
     *
     * .
     *
     */
    public function testProcurementUnitOfMeasuresIdConversionsConversionIdPut()
    {

    }

    /**
     * Test case for procurementUnitOfMeasuresIdConversionsCountGet
     *
     * .
     *
     */
    public function testProcurementUnitOfMeasuresIdConversionsCountGet()
    {

    }

    /**
     * Test case for procurementUnitOfMeasuresIdConversionsGet
     *
     * .
     *
     */
    public function testProcurementUnitOfMeasuresIdConversionsGet()
    {

    }

    /**
     * Test case for procurementUnitOfMeasuresIdConversionsPost
     *
     * .
     *
     */
    public function testProcurementUnitOfMeasuresIdConversionsPost()
    {

    }

}
